plugins:
  - serverless-latest-layer-version
  - serverless-offline

service: stats-api
app: tally-backend
org: aroger7

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource: '*'
  environment:
    ORM_LAYER_PATH: ${env:ORM_LAYER_PATH, '/opt/db'}
    DB_SECRET_NAME: ${env:DB_SECRET_NAME, param:DB_SECRET_NAME}

functions:
  statsApi:
    handler: index.handler
    name: ${sls:stage}-stats-api-function
    events:
      - http:
          path: graphql
          method: POST
          cors: true
          private: false
    layers:
      - arn:aws:lambda:${opt:region, 'us-east-1'}:#{AWS::AccountId}:layer:${sls:stage}-orm-layer:latest
